### ISSUE TITLE
Support for attaching to debugger listening on websocket connection

### ISSUE THREAD

**Issue by DavFeng1** [mxsdev/nvim-dap-vscode-js#16]
Been trying to get this working by spinning up a  `node` process with the `--inspect-brk` flag.
```
Debugger listening on ws://127.0.0.1:9229/133fb593-50c7-4e71-b9fb-7269906ca972
For help, see: https://nodejs.org/en/docs/inspector
```
I noticed that when running the debugger in Neovim I get the error message 
```
[dap-js] JS Debugger stderr: Error: Could not connect to debug target at http://127.0.0.1:9222: Could not find any debuggable target
```
Notice the `http` in the debug target. Is there some way to point at the websocket connection above? 

Thanks!

**Comment by milogert** [comment]
@DavFeng1 I'm getting this exact same error. How did you resolve this?
