### ISSUE TITLE
Why the `pwa-` prefixes?

### ISSUE THREAD

**Issue by mawkler** [mxsdev/nvim-dap-vscode-js#29]
I noticed that nvim-dap-vscode-js doesn't work for `launch.json` tasks that don't have the `"task"` value prefixed with `pwa-` (like `"pwa-node"`). According to https://github.com/microsoft/vscode-js-debug/issues/1404, `pwa-` should no longer be used. Are there any plans to remove the `pwa-` prefixes for nvim-dap-vscode-js and/or also support `launch.json` files with just `"node"`, `"chrome"`, etc.?

**Comment by mxsdev** [comment]
See the discussion in #13. 

I wish I had more time to work on stuff like this repo, but I am definitely open to PRs if you're interested :)

Feel free also to re-open if the discussion #13 doesn't cover what you're talking about.
