### ISSUE TITLE
Support variable entry-point file name?

### ISSUE THREAD

**Issue by mikaoelitiana** [mxsdev/nvim-dap-vscode-js#40]
The entry-point file name is hard-coded here : 
https://github.com/mxsdev/nvim-dap-vscode-js/blob/03bd29672d7fab5e515fc8469b7d07cc5994bbf6/lua/dap-vscode-js/utils.lua#L53

But it may change depending on the version and installation tool used. For my case, I installed `js-debug-adapter` using [mason](https://github.com/williamboman/mason.nvim) and the bin path is defined [here](https://github.com/mason-org/mason-registry/blob/b0ce4f8d873395bf8300faa03496f0724336fdb5/packages/js-debug-adapter/package.yaml#L13-L19). 

What do you think of making the file path `out/src/vsDebugServer.js` also configurable just like `debugger_path` so it can be changed as needed for other installation processes?

**Comment by RedactedProfile** [comment]
I just installed nvim-dap-vscode-js and microsoft/vscode-js-debug today, and the filename is now `vsDebugServer.ts` 

Error:
![image](https://user-images.githubusercontent.com/1039911/230216851-67082787-1d36-487c-a364-d8f61807a805.png)

Filesystem
![image](https://user-images.githubusercontent.com/1039911/230216967-220e7558-ec20-4700-8e13-04e1e973d751.png)

**Comment by mxsdev** [comment]
This will be fixed as part of #38.

Sorry for the delay, I moved over the past week and that has taken up most of my time.

**Comment by RedactedProfile** [comment]
please ignore my response. I'm a newbie and didn't realize that after having installed the plugin, that I had to then go in and manually build it with gulp. 

But also now, the other issue is that the path is absolutely valid, including doing the `mv dist out` and it's still reporting the file missing 🤔

**Comment by mikaoelitiana** [comment]
Thank you very much @mxsdev, you are doing an awesome work!!
