### ISSUE TITLE
pwa-node config for nestjs projects

### ISSUE THREAD

**Issue by zilverjk** [mxsdev/nvim-dap-vscode-js#41]
Hello 
I would like to know how I can configure correctly the adapter in order to get work the debugger?. 
This is my current config 

```lua
{
			type = "pwa-node",
			request = "launch",
			name = "NestJS: Launch",
			-- runtimeExecutable = "nest",
			program = "${workspaceFolder}/src/main.ts",
			cwd = "${workspaceFolder}",
			skipFiles = {
				"<node_internals>/**",
			},
			sourceMaps = true,
			resolveSourceMapLocations = {
				"${workspaceFolder}/**",
				"!**/node_modules/**",
			},
			protocol = "inspector",
			console = "integratedTerminal",
			port = 3000,
			-- args = { "start", "--watch", "--debug" },
			env = {
				NODE_ENV = "dev",
			},
			outFiles = {
				"${workspaceFolder}/dist/main.js",
			},
			sourceMapPathOverrides = {
				["webpack:///./src/*"] = "${workspaceFolder}/src/*",
				["webpack:///src/*"] = "${workspaceFolder}/src/*",
				["webpack:///*"] = "*",
			},
		},
``` 

With this config I get an error in the repl following the debug disconnect when Im trying to lunch the debug
<img width="1482" alt="Screenshot 2023-04-07 at 8 05 04 PM" src="https://user-images.githubusercontent.com/7515854/230696822-4767ef85-feb1-45ea-ad39-77d914cd208e.png">

And this is my tsconfig.js

<img width="398" alt="image" src="https://user-images.githubusercontent.com/7515854/230696853-58ac3cde-3268-4257-beb2-ca804ccf792a.png">

thanks for the help in advance.

**Comment by gbarandiaranwefox** [comment]
I'm having the same issue!

**Comment by zilverjk** [comment]
Forget the adapter config of the issue, use the default and start the nest app with this command
`node --inspect ./dist/main.js` and the debugger will start
