### ISSUE TITLE
Error trying to launch JS debugger: EACCES: permission denied

### ISSUE THREAD

**Issue by Hugobsb** [mxsdev/nvim-dap-vscode-js#54]
Hello! I would like to know how I can debug this issue.

# Issue

This is all the information I was given.

Using `cat` on the log output after setting the `log_level` to `4` gives me the following output:

```
[ERROR qua 19 jul 2023 19:21:50 27324356607905] ...im/lazy/nvim-dap-vscode-js/lua/dap-vscode-js/adapter.lua:72: Error trying to launch JS debugger: EACCES: permission denied
```
(the `...` came together)

I'm also able to see it in the terminal:

![image](https://github.com/mxsdev/nvim-dap-vscode-js/assets/58279735/a59fd498-2c31-453d-9430-c4dbca9a9a04)

# Attempts

Just to be sure, I tried to run `sudo chmod +rx -R ./directory` where `directory` was every folder related do dap that I have here.

Output of `ls -l` on the dap files:

```
drwxrwxr-x  8 hugo hugo 4096 jul 19 16:09 nvim-dap
drwxrwxr-x  8 hugo hugo 4096 jul 19 16:16 nvim-dap-ui
drwxrwxr-x  7 hugo hugo 4096 jul 19 16:35 nvim-dap-virtual-text
drwxrwxr-x  8 hugo hugo 4096 jul 19 17:16 nvim-dap-vscode-js
drwxrwxr-x 12 hugo hugo 4096 jul 19 19:20 vscode-js-debug
```

I also tried to edit the project on my own to use `logger.error` to see in which line the error happens, but my nvim failed to start with the edited project. Thus, I abandoned this approach.

# Setup information

Operational System
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

Neovim
```
NVIM v0.10.0-dev-530+g8376e8700
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/build/nvim/parts/nvim/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Everything related to dap is in the most recent changes of the `master` branches.

- - -
Let me know if you need more information. Plus, feel free to reach me on Discord `hugobsb`.

**Comment by Hugobsb** [comment]
I don't have any clue of what exactly doesn't have sufficient permission.

**Comment by Hugobsb** [comment]
Solved [here](https://github.com/mxsdev/nvim-dap-vscode-js/issues/8). My bad, I haven't seen it before.

**Comment by wyrjob** [comment]
👍
