### ISSUE TITLE
Got error "adapter.port is required for server adapter" when using manson installed vscode-js-debug

### ISSUE THREAD

**Issue by BilderLoong** [mxsdev/nvim-dap-vscode-js#58]
[My lazy.nvim plugin config](https://github.com/BilderLoong/dotfiles/blob/bd3fdefebaaff4de381b10db994288e7f6e41dab/nvim/.config/nvim/lua/custom/plugins.lua#L427-L468):
```lua
{
    "mxsdev/nvim-dap-vscode-js",
    ft = { "javascript", "javascriptreact", "typescript", "typecriptreact" },
    dependencies = { "mfussenegger/nvim-dap" },
    opts = function(_, default_nvchad_opts)
      return {
        node_path = "node",
        debugger_cmd = { "js-debug-adapter" }, -- Command to use to launch the debug server. Takes precedence over `node_path` and `debugger_path`.
        adapters = { "pwa-node", "pwa-chrome", "pwa-msedge", "node-terminal", "pwa-extensionHost", "node", "chrome" },
      }
    end,
    config = function(_, opts)
      require("dap-vscode-js").setup(opts)

      for _, language in ipairs { "typescript", "javascript" } do
        require("dap").configurations[language] = {
          {
            type = "pwa-node",
            request = "attach",
            name = "Attach",
            processId = require("dap.utils").pick_process,
            cwd = "${workspaceFolder}",
          },
          {
            -- use nvim-dap-vscode-js's pwa-node debug adapter
            type = "pwa-node",
            -- launch a new process to attach the debugger to
            request = "launch",
            -- name of the debug action you have to select for this config
            name = "Launch current file in new node process (" .. language .. ")",
            program = "${file}",
            cwd = "${workspaceFolder}",
          },
        }
      end
    end,
  }
```

Full error message:
```
Error executing luv callback:
...rudo/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1307: adapter.port is required for server adapter
stack traceback:
        [C]: in function 'assert'
        ...rudo/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1307: in function <...rudo/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1299>
Press ENTER or type command to continue
```

**Comment by BilderLoong** [comment]
I think this error is because the lua pattern used to extract the debug server port 

https://github.com/mxsdev/nvim-dap-vscode-js/blob/03bd29672d7fab5e515fc8469b7d07cc5994bbf6/lua/dap-vscode-js/utils.lua#L117
isn't compatible with the output of the `js-debug-adapter` which actually run the [js-debug/src/dapDebugServer.js](https://github.com/microsoft/vscode-js-debug/blob/main/src/dapDebugServer.ts) file.
Output of running `js-debug-adapter`.
```
$ cat js-debug-adapter
#!/usr/bin/env bash

exec node "/Users/birudo/.local/share/nvim/mason/packages/js-debug-adapter/js-debug/src/dapDebugServer.js" "$@"%

$ ./js-debug-adapter
Debug server listening at 127.0.0.1:8123
```

**Comment by BilderLoong** [comment]
Related to https://github.com/mxsdev/nvim-dap-vscode-js/issues/57.

**Comment by carlos-algms** [comment]
Hey @BilderLoong, there have been no new commits to this repo since last Year. 
Could you point out the solution you got? 
Thanks.

**Comment by navignaw** [comment]
@carlos-algms I followed the workaround in https://github.com/mxsdev/nvim-dap-vscode-js/issues/57#issue-1890647297 to lock to version 1.76.1 to fix the issue. If you use https://github.com/jay-babu/mason-nvim-dap.nvim then the solution would look something like

```lua
require("mason-nvim-dap").setup({
  automatic_installation = false,
  ensure_installed = {
    -- Due to a bug with the latest version of vscode-js-debug, need to lock to specific version
    -- See: https://github.com/mxsdev/nvim-dap-vscode-js/issues/58#issuecomment-2213230558
    "js@v1.76.1",
  },
})
```

Or if you install it manually, `MasonInstall js-debug-adapter@v1.76.1` (you may need to run `MasonUninstall` first to remove the later version)

**Comment by ecosse3** [comment]
Is anyone experiencing the same issue again? Locking the version to `v1.76.1` of `js-debug-adapter` in Mason worked for me for a couple of months, but I'm starting to get the same issue again now.

![image](https://github.com/user-attachments/assets/24e7a828-6003-4181-9606-58d928caa059)

**Comment by janwvjaarsveld** [comment]
This comment worked for me: https://github.com/mfussenegger/nvim-dap/issues/1411#issuecomment-2566396879

**Comment by Nirajgns** [comment]
could you please share your dap config...?

**Comment by janwvjaarsveld** [comment]
> could you please share your dap config...?

```lua

require("dap").adapters["pwa-node"] = {
        type = "server",
        host = "localhost",
        port = "${port}",
        executable = {
          command = "node",
          -- 💀 Make sure to update this path to point to your installation
          args = {
            "~/.local/share/nvim/mason/packages/js-debug-adapter/js-debug/src/dapDebugServer.js",
            "${port}",
          },
        },
      }
```

**Comment by gonzastoll** [comment]
For anyone coming here for the resurgence of this issue, borrowing some stuff from `LazyVim` fixed the issue. What I did was:
* Removed the `nvim-dap-vscode-js` plugin
* Configured the adapter manually:

```lua
--- Gets a path to a package in the Mason registry.
--- Prefer this to `get_package`, since the package might not always be
--- available yet and trigger errors.
---@param pkg string
---@param path? string
local function get_pkg_path(pkg, path)
  pcall(require, 'mason')
  local root = vim.env.MASON or (vim.fn.stdpath('data') .. '/mason')
  path = path or ''
  local ret = root .. '/packages/' .. pkg .. '/' .. path
  return ret
end

require('dap').adapters['pwa-node'] = {
  type = 'server',
  host = 'localhost',
  port = '${port}',
  executable = {
    command = 'node',
    args = {
      get_pkg_path('js-debug-adapter', '/js-debug/src/dapDebugServer.js'),
      '${port}',
    },
  },
}
```

**Comment by Nirajgns** [comment]
How do you set it up for frontend, chrome?

**Comment by gonstoll** [comment]
> How do you set it up for frontend, chrome?

It's been a while since I last used it, so I'm not sure if it still works, but [this is the config that I used](https://github.com/gonstoll/dotfiles/blob/master/.config/nvim/lua/plugins/dap.lua#L281-L322) for debugging frontend code on chrome. Keep in mind, this is not an adapter configuration, but rather a task configuration.

**Comment by dsypasit** [comment]
@gonzastoll finally work! very thanks for sharing!
