### ISSUE TITLE
Error trying to launch JS debugger: EACCES: permission denied 

### ISSUE THREAD

**Issue by MB-Izzo** [mxsdev/nvim-dap-vscode-js#8]
When installing, `Error trying to launch JS debugger: EACCES: permission denied ` is thrown when I try to launch the debugger. It seems that it happens with both recommended installation methods (manual and with packer).

My $USER have access to the file.
`-rwxrwxr-x  1 myUser myUser  5635 août  27 00:24 vsDebugServer.js`

**Comment by mxsdev** [comment]
Sorry for the late reply - I presume you figured out the issue?

**Comment by perrin4869** [comment]
I just ran into this. In my case, the cause was that `NODE_PATH` was set to `/usr/lib64/node_modules`.
The solution in my case was to set `node_path` option to `node` explicitly.
Maybe this will help someone else who runs into this.

**Comment by quin-aot** [comment]
Hi! I am also having this issue. I am using nvm and do not have a `NODE_PATH` env var. Any ideas on what could be causing this?
